name: Publish npm and github release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-release:
    name: Tagged Release
    runs-on:  ubuntu-20.04    

    steps:
      - name: Checkout source
        uses: actions/checkout@v2        
      
      - name: Install Node      
        uses: actions/setup-node@v1 
        with:
          node-version: '14'          

      - name: build and test
        run: | 
          npm ci
          npm run build && npm run test

      - name: Prepare package
        run: npm pack         

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}          
          prerelease: false
          files: |
            LICENSE
            *.tgz

      - name: Publish on npmjs
        run: echo "Not yet implemeted !"
      # - run: npm publish
      # - uses: JS-DevTools/npm-publish@v1
      #   with:
      #     token: ${{ secrets.NPM_AUTOMATION_TOKEN }}  
            